######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 1 00:33:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . source
INCLUDEPATH += . source

QT += network

# Input
SOURCES += source/*

# Output
OBJECTS_DIR += .build
